### PR TITLE
fixed: broken keyword in e576f399f18da63172aa983d3f630e05111e2b0d

### PR DESCRIPTION
**Pull request by akva2**
A mere compilation test showed the failure here.

Repeat after me: I WILL NEVER EVER PULL UNTESTED CODE INTO A PRODUCTION GIT.  Now go repeat it 10000 times bart simpson style until it sticks.

### CODE REVIEW

**Comment by akva2** [comment]
note that my fix may we off if an enum value NONE was intended.

**Comment by GitPaean** [comment]
Sorry. I did compile, while I am not sure why I did not see the problem. I will try it again now. Thanks for the fix.

**Comment by akva2** [comment]
that's a bit disconcerning. it's likely that a clean build that caused the problem. is there a dependency tracking issue in the buildsystem. @joakim-hove perhaps ?

**Comment by GitPaean** [comment]
Now I see it is broken. Thanks for the fix. I saw another error when compiling and I corrected it. I did not see this one. Sorry for that.

**Comment by akva2** [comment]
right. that explains it. the build system is based on globbing for keywords. since your commit was a pure keyword-add it wouldn't cause a rebuild and you wouldn't see the issue. you likely edited the file after it built right?

**Comment by GitPaean** [comment]
Maybe, while I am not sure about that.

**Comment by joakim-hove** [comment]
Ok: my bad. Travis was slow to start so I just tought what the ....

The build system has a dependency checking on the keywords which I thougt worked,  but I guess you can fool it.

Will wait for Travis now.

**Comment by pgdr** [comment]
While I normally _insist_ on waiting for Travis, in this case I would say that we can just merge.  If it still fails, it's something more that needs to be done, but this fix needs to go in anyway.

**Pull request merged**
