### PR TITLE
Basic support for cylindrical grids

### PR DESCRIPTION
**Pull request by joakim-hove**
With this PR the EclipseGrid implementation has limited support for radial grids. The grid must be specified using the keywords `DRV, DTHETAV, DZV`and `TOPS`. When the radial grid is specified this way everything - including simulation and ouptut migth actually *Just Work*&trade;

### CODE REVIEW

**Comment by joakim-hove** [comment]
Does anyone care? I'll just merge this tomorrow.

**Comment by atgeirr** [comment]
I care, but have not tested this. I assume that it just works... About simulation just working, I would not expect that. At least we must ensure the grid has connections across the periodic boundary of the input grid.

**Comment by joakim-hove** [comment]
> At least we must ensure the grid has connections across the periodic boundary of the input grid.

Yes - the actual connection must be established in opm-grid, but the `EclipseGrid` has got the new method `circle( )` which return `true` iff such a periodic connection should be added in the simulation grid.

**Comment by atgeirr** [comment]
> Yes - the actual connection must be established in opm-grid, but the EclipseGrid has got the new method circle( ) which return true iff such a periodic connection should be added in the simulation grid.

Sounds good!

**Comment by atgeirr** [comment]
jenkins build this with downstreams please

**Pull request merged**
