### PR TITLE
ENABLE_PYTHON in opm-parser/jenkins

### PR DESCRIPTION
**Pull request by joakim-hove**

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this please

**Comment by akva2** [comment]
this will be fine for the pr builder and the post-merge builder but this is not used for downstreams or when opm-parser is an upstream.

you have to add to the list here https://github.com/OPM/opm-common/blob/master/jenkins/build-opm-module.sh#L84 for downstreams and https://github.com/OPM/opm-common/blob/master/jenkins/build-opm-module.sh#L61 for upstream. yes, i'm not entirely satisified with how it's currently factored..

**Comment by joakim-hove** [comment]
> you have to add to the list here [....]

OK - thank you.

**Comment by joakim-hove** [comment]
jenkins build this with downstream opm-common=151 please

**Comment by joakim-hove** [comment]
jenkins build this with downstreams opm-common=151 please

**Pull request merged**
