### PR TITLE
Split parser interface into public/private components

### PR DESCRIPTION
**Pull request by jokva**
This is the first PR in a series to encapsulate the internals of opm-parser better, and have a clear split on public/private interfaces. The endgame is to be able to move faster internally, provide a more stable programming interface for downstream and eventually mature and version the public interface.

The PR itself is huge, but is largely renames. A brief overview:

* A new directory, `eclipse/bits` is introduced. Internal headers will go here, and if one of these headers are included we *do not guarantee* anything w.r.t. stability, availability or breakage. Use at your own risk.
* EclipseState, Parser, and Units, are moved to `eclipse`. Files directly under `eclipse` are meant to be included by users, and when we mature it should be sufficient to include these headers in your project to fully leverage opm-parser. This also means that if you include these headers (or a subset of them) we will maintain includes for new features.
* The `Deck` class is moved into `eclipse/bits` and is considered internal. There will be a grace period, but querying `Deck` instances directly will from now on be considered unsupported. Once downstream is properly ported we might even stop *installing* the Deck headers on user systems, making them a build-time detail.
* `Deck` is no longer a part of `Parser`'s interface.

The final point is the only behavioural change in this PR. Including `Parser.hpp` will no longer provide the `Deck` declaration. This also means the static methods `Parser::parse, Parser::parseFile` etc. are gone. They have been replaced (essentially renamed) by the function `ecl::parse`, declared in EclipseState.hpp. The final interface is still up for discussion, and I'd love feedback on the solution.

The moving of files was done doing roughly this:
```
1. mv {Deck, RawDeck, Utility, Generator} -> bits/
2. find -name "*.[ch]pp" -exec sed -i 's,/Deck/,/bits/Deck/,' {} \;
3. mv {EclipseState/EclipseState.hpp} -> EclipseState.hpp
4. mv {Parser/Parser.hpp} -> Parser.hpp
5. find -name "*.[ch]pp" -exec sed -i 's,EclipseState/EclipseState.hpp,EclipseState.hpp,' {} \;

```

edit: 
PS. Notice that `bits/Parsers.hpp` isn't installed on user systems. This is by design.
PPS. I intend to later extend `bits/Parsers.hpp` with other input -> public object functions to hide the deck implementation detail.
PPS. First PS is wrong, `bits/Parsers.hpp` is installed.

### CODE REVIEW

**Comment by andlaus** [comment]
First of all, I think this PR changes things for the better! while at it, what are the plans to reorganize the module in order to *remove* some directory levels? (IMO places like `opm/parser/eclipse/EclipseState/SummaryConfig/tests` are not exactly intuitive.)

**Comment by jokva** [comment]
Still under discussion, but there will most likely be EclipseState/Schedule/, EclipseState/Grid and the rest just under EclipseState. No guarantees though.

**Comment by andlaus** [comment]
can `opm/parser/eclipse` shortened to `opm/parser`? (the entropy `eclipse` is zero if everything is in that directory.)

**Comment by jokva** [comment]
Probably not, we're still toying with the idea of multiple frontends.

**Comment by jokva** [comment]
> PS. Notice that bits/Parsers.hpp isn't installed on user systems. This is by design.

I have to take this back, I have to install it for now because opm-material uses Deck so much.

**Comment by pgdr** [comment]
This PR perfectly addresses issues raised in #795 — _Difficult api: EclipseDeck?_

**Comment by atgeirr** [comment]
> This PR perfectly addresses issues raised in #795 — Difficult api: EclipseDeck?

A bit along the way, yes. I do think that we should *not* make Deck private. That (by requiring EclipseState) will eventually break lots of code that currently works well on imperfect/invalid/sectionless decks.

I don't understand why we need the Parser class to be public though, other than as a gateway to Deck and EclipseState?

**Comment by jokva** [comment]
> A bit along the way, yes. I do think that we should not make Deck private. That (by requiring EclipseState) will eventually break lots of code that currently works well on imperfect/invalid/sectionless decks.

Deck should still be private, but a part of that process is being able to instantiate sub objects of eclipsestate (which is largely an aggregate of these) with relaxed requirements to deck completeness.

> I don't understand why we need the Parser class to be public though, other than as a gateway to Deck and EclipseState?

User-modifyable behaviour of the parsing process. This is mostly uninteresting from flow, but there are other applications where this can be useful. For flow and similar applications doing `ecl::parse( inputfile )` should be sufficient.

**Comment by atgeirr** [comment]
> Deck should still be private, but a part of that process is being able to instantiate sub objects of eclipsestate (which is largely an aggregate of these) with relaxed requirements to deck completeness.

If we call the Deck interface "level 1" and the EclipseGrid etc. interface "level 2" (and the EclipseState being a validated set of level 2 things): I take this to mean that you intend to provide level 2 interfaces for absolutely every single possible keyword/feature? I think that sounds like a *lot* of work, especially as we move to the clients that are not Flow. Are you sure this is worth giving such a high priority?

If it is, then by all means: I like how for example the EclipseState takes away the need to understand many gory details, and would appreciate all the level 2 interfaces.

**Comment by jokva** [comment]
If EclipseState or similar facilities aren't providing it then it will be re-implemented by the downstream that need it, often poorly and without proper context. I'd rather see that be a contribution to parser. So in a sense, yes.

**Comment by pgdr** [comment]
@jokva this must probably be rebased after the jfunc; but then I think we want to merge this as soon as possible.  @joakim-hove do you have any comments before a potential merge?

**Comment by jokva** [comment]
@pgdr Rebasing isn't a problem. I have a couple of other PRs that should go first though, https://github.com/OPM/opm-parser/pull/1016 https://github.com/OPM/opm-parser/pull/1015 and respective downstreams (and the additions they will spawn).

**Comment by joakim-hove** [comment]
Closing in agreement with @jokva.

**Pull request closed without merging**
