### PR TITLE
Support for minpv-pinch-nnc 

### PR DESCRIPTION
**Pull request by totto82**
Adds 
- default constructor
- non-const access of the nncs
- test

### CODE REVIEW

**Comment by joakim-hove** [comment]
> non-const access of the nncs

Hmmm - why do need that?

> When this code is revisited I would strongly prefer that it was implemented as a vector of:
struct NNC {
    size_t cell1;
    size_t cell2;
    double trans;
}
```

Instead of three `std::vector<>` instances.

**Comment by atgeirr** [comment]
> When this code is revisited I would strongly prefer that it was implemented as a vector of:
> 
> ```
> struct NNC {
>     size_t cell1;
>     size_t cell2;
>     double trans;
> }
> ```
> Instead of three std::vector<> instances.

I think that where the class is used (in opm-autodiff) it is more convenient to have the separate vectors, at least for the transmissibilities. I do agree that the structure you propose is a little more intuitive though.

**Comment by totto82** [comment]
The nnc data is stored in  a structure, NNCdata, as you suggested.

**Comment by joakim-hove** [comment]
> The nnc data is stored in a structure, NNCdata, as you suggested.

Thank you. I am ready to merge this - but I will hold back until someone gives a green light for the downstream module. The downstream reviewer @atgeirr / @bska ?? is welcome to push green on this as well.

**Comment by atgeirr** [comment]
The whole chain of PRs should now be good, I will therefore merge this, since @joakim-hove gave his OK. Thanks for the effort!

**Pull request merged**
