### PR TITLE
Add support for PVDS

### PR DESCRIPTION
**Pull request by totto82**
-the PVDS implementation is essentially a copy of the PVDG
implementation as the PVDS table analogous the PVDG table

### CODE REVIEW

**Comment by atgeirr** [comment]
Why not use the PVDG table class then?

**Comment by andlaus** [comment]
> Why not use the PVDG table class then?

that's basically because of the fundamental design of the table abstraction classes: the names of the columns are probably slightly different between PVTG and PVTS, the columns could have different constraints, etc. Besides this, the reason for having a separate class for each table is that in the higher layers you're forced to go on different code paths for different functionality.

If you look at the patch, you'll see that the class itself is not much copy-and-pasted code. (and the boiler-plate code in EclipseState would be required in any case...)

**Comment by joakim-hove** [comment]
The new file `PvdsTable.hpp` is missing from the list of included files.

**Comment by joakim-hove** [comment]
I really think the table classes should be refactored one shiny day - but I will merge this now (when the `CMakeLists.txt` file has been updated).

**Comment by totto82** [comment]
The new file is now added.

**Pull request merged**
