### PR TITLE
Updates / fixes in tests

### PR DESCRIPTION
**Pull request by joakim-hove**

### CODE REVIEW

**Comment by bska** [comment]
I'm seeing build failures in my `-j ${N}` builds of opm-parser in fresh build trees; `-j1` is fine.  `git bisect` suggests that commit d275063 may have inadvertently removed some essential dependency information with respect to the generated source code.  Is this PR in any way related?  Would you like me to test it?

**Comment by joakim-hove** [comment]
Yes - this PR is my attempt to fix those build problems, must admit that I
did not really understand the problem - which always a bad sign.

Cool if you test it.
26. mai 2015 20:33 skrev "Bård Skaflestad" <notifications@github.com>
følgende:

**Comment by akva2** [comment]
see https://github.com/OPM/opm-cmake/pull/11 for core of issue. i'd prefer you change back to use the macro.

**Comment by bska** [comment]
> Cool if you test it.

For what it's worth, this patch survived my nightly "full" run.  In other words, this does at least treat the symptom.

**Comment by joakim-hove** [comment]
OK - this has been updated to use the `opm_add_test()` macro along with: https://github.com/OPM/opm-cmake/pull/11 - looks good.

**Pull request merged**
