### PR TITLE
TableManager.getPvtwTable

### PR DESCRIPTION
**Pull request by jokva**
Provide a richer interface to read the PVTW table.

### CODE REVIEW

**Comment by jokva** [comment]
Downstream: https://github.com/OPM/opm-core/pull/1119

**Comment by joakim-hove** [comment]
This does not belong with `InirConfig` - only the *implementation* resembles `EQUIL` - not the reservoir content.

**Comment by jokva** [comment]
Alright. It's a table, then, I presume?

**Comment by joakim-hove** [comment]
Yes - I guess table is the best match.

**Comment by jokva** [comment]
Updated. I'll re-push core as well.

**Comment by jokva** [comment]
Restarting CI.

**Pull request merged**
