### PR TITLE
[WIP and discussion] Fixing history mode

### PR DESCRIPTION
**Pull request by GitPaean**
The tests have not been fixed and tested. 

The observed rates not under control from keyword will not become control/limit. 

For both WCONHIST and WCONINJH, the bhp control will always be there. For WCONHIST, the default BHP limit will be 1 atm. For WCONINJH, it is a large value (It can be the 8925 bar as WCONINJE, while has not found proof).

WELTARG can be used to set the BHP limit for both keywords. For WCONHIST, the BHP limit set by WELTARG can be changed by WCONHIST under BHP control mode. 

For WCONINJH, the BHP limit set by WELARG will not be affected by information specified by WCONINJH keyword. 

FBHPDEF can be used to set the default BHP limits, while the keyword has not been implemented yet. 

This PR still use same variables to represent the rate limits and observed rates (depending whether prediction mode and historical mode), not sure whether it is desired. Please suggest.  It looks like to me compatible with the opm-output. 

The related PR in opm-simulators is coming.

### CODE REVIEW

**Comment by joakim-hove** [comment]
> The tests have not been fixed and tested.

Well - then I close this now.

**Comment by GitPaean** [comment]
It is created for discussion.

**Comment by joakim-hove** [comment]
Well - we'll discuss this offline; I tried calling you - will try again.

**Comment by GitPaean** [comment]
Sorry, I did not see your call. But I saw there is something I need to fix now.

**Comment by GitPaean** [comment]
The `ScheduleTests.cpp` contains a situation I am really not sure. 
In the test case, `changeBhpLimitInHistoryModeWithWeltarg`
```
1151             "/\n"
1152             "WCONHIST\n"
1153             " 'P' 'OPEN' 'RESV' 6*  500 / \n"
1154             "/\n"
1155             "WCONINJH\n"
1156             " 'I' 'WATER' 1* 100 250 / \n"
1157             "/\n"
1158             "WELTARG\n"
1159             "   'P' 'BHP' 50 / \n"
1160             "   'I' 'BHP' 600 / \n"
1161             "/\n"
1162             "DATES             -- 2\n"
1163             " 15  OKT 2008 / \n"
1164             "/\n"
1165             "WCONHIST\n"
1166             "   'P' 'OPEN' 'RESV' 6*  500/\n/\n"
1167             "WCONINJH\n"
1168             " 'I' 'WATER' 1* 100 250 / \n"
1169             "/\n"
1170             "DATES             -- 3\n"
1171             " 18  OKT 2008 / \n"
1172             "/\n"
1173             "WCONHIST\n"
1174             "   'I' 'OPEN' 'RESV' 6*  /\n/\n"
1175             "DATES             -- 3\n"
1176             " 20  OKT 2008 / \n"
1177             "/\n"
1178             "WCONINJH\n"
1179             " 'I' 'WATER' 1* 100 250 / \n"
1180             "/\n"
1181             ;
```

The well `I` is claimed to be injector (WCONINJH), then producer(WCONHIST), then injector(WCONINJH).  Based on the `RESV`, I think it was intentional. I will fix to not to make it a producer through `WCONHIST`.

**Comment by GitPaean** [comment]
I took back partly my above comment. But `RESV` is not allowed with WCONINJH.

**Comment by GitPaean** [comment]
I could not reopen this PR due to forced push, so I opened a new one.

**Comment by GitPaean** [comment]
I could not reopen this PR due to forced push, so I opened a new one.

**Pull request closed without merging**
