### PR TITLE
Adding keyword SHRATE.

### PR DESCRIPTION
**Pull request by GitPaean**
Adding the keyword SHRATE, which should be used together with PLYSHLOG. 

The most difficult part for this keyword is that it will change the unit of the PLYSHLOG keyword. 

Please suggest how we can achieve that. Thanks.

### CODE REVIEW

**Comment by joakim-hove** [comment]
> Please suggest how we can achieve that

I'm sorry to say that we do not really have a good system for these situations; there are a handful of context dependent dimensions like this. Currently the only feasible way is to let the `PLYSHLOG` keyword be dimensionless and then use application logic to apply the correct dimension. See e.g. https://github.com/OPM/opm-parser/blob/master/opm/parser/eclipse/EclipseState/Schedule/Schedule.cpp for how this is handled with `WELTARG`keyword. To achieve this the `DATA` item of the `PLYSHLOG` keyword must be made fully dimensionless.

The `SHRATE` keyword of this PR looks perfectly OK, but I will await changes in the Polymer code + `PLYSHLOG` before merging.

**Comment by joakim-hove** [comment]
When it is fully dimensionless I would just remove the `"dimension" :` attribute, and use `DekcDoubleItem::getRawDouble()`method in calling scope.

**Comment by GitPaean** [comment]
You mean for all the parameters in the `PLYSHLOG`, right? I think only the first column of the `PLYSHLOG` table is affected. 

And also, you mean, in `opm-parser` I just need to make the `PLYSHLOG` in `opm-parser' dimensionless and do all the unit conversion in `opm-polymer`. Please let me know if I understood correctly. Thanks.

**Comment by joakim-hove** [comment]
> You mean for all the parameters in the PLYSHLOG, right?

No - I mean the `DATA` item in the second record; the items in the first record are not affected and should retain their dimension.

**Comment by joakim-hove** [comment]
Good - I am happy to merge this now; but I guess some updates will be required in the polymer code as well. Do you want me merge this now - or should I hold back until opm-polymer is ready?

**Comment by GitPaean** [comment]
Please do not merge now. The polymer code is still in my own branch and it still need some time to adapt to the recently re-factored from. I will let you know when everything is tested and ready from the `opm-polymer` side.  Thanks.

**Comment by GitPaean** [comment]
Hi, I think it implies some problem for future, right. I guess more things need to be done in `opm-parser`. 

```
~/OPM/build/opm-parser-build/bin/opm-eclkwtest 2D_THREEPHASE_POLY_HETER.DATA 
terminate called after throwing an instance of 'std::invalid_argument'
  what():  No dimension has been set for item:DATA can not ask for SI data
Aborted
```

**Comment by joakim-hove** [comment]
Hmmm - seems to work for me. Please run in debugger and post a backtrace?

**Comment by GitPaean** [comment]
I can send you the data for experiment if you need it. Thanks. 

```
(gdb) set args 2D_THREEPHASE_POLY_HETER.DATA 
(gdb) run
Starting program: /home/kaib/OPM/debug/opm-parser-build/bin/opm-eclkwtest 2D_THREEPHASE_POLY_HETER.DATA 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
terminate called after throwing an instance of 'std::invalid_argument'
  what():  No dimension has been set for item:DATA can not ask for SI data

Program received signal SIGABRT, Aborted.
0x00007ffff68abcc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) backtrace 
#0  0x00007ffff68abcc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff68af0d8 in __GI_abort () at abort.c:89
#2  0x00007ffff71b76b5 in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff71b5836 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff71b5863 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff71b5aa2 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x000000000083ae21 in Opm::DeckDoubleItem::assertSIData (this=0xc04328) at /home/kaib/OPM/debug/opm-parser/opm/parser/eclipse/Deck/DeckDoubleItem.cpp:55
#7  0x000000000083ae91 in Opm::DeckDoubleItem::getSIDouble (this=0xc04328, index=0) at /home/kaib/OPM/debug/opm-parser/opm/parser/eclipse/Deck/DeckDoubleItem.cpp:62
#8  0x00000000007f9063 in Opm::SingleRecordTable::getFlatSiDoubleData (this=0xbecff0, deckRecord=..., flatItemIdx=0) at /home/kaib/OPM/debug/opm-parser/opm/parser/eclipse/EclipseState/Tables/SingleRecordTable.cpp:266
#9  0x00000000007f7af0 in Opm::SingleRecordTable::init (this=0xbecff0, keyword=..., columnNames=..., recordIdx=1, firstEntityOffset=0) at /home/kaib/OPM/debug/opm-parser/opm/parser/eclipse/EclipseState/Tables/SingleRecordTable.cpp:50
#10 0x00000000007629a4 in Opm::PlyshlogTable::init (this=0xbec1c0, keyword=...) at /home/kaib/OPM/debug/opm-parser/opm/parser/eclipse/EclipseState/Tables/PlyshlogTable.hpp:76
#11 0x000000000074b9dd in Opm::EclipseState::initPlyshlogTables (this=0x7fffffffdad0, deck=..., keywordName=..., tableVector=...) at /home/kaib/OPM/debug/opm-parser/opm/parser/eclipse/EclipseState/EclipseState.cpp:651
#12 0x0000000000747729 in Opm::EclipseState::initTables (this=0x7fffffffdad0, deck=...) at /home/kaib/OPM/debug/opm-parser/opm/parser/eclipse/EclipseState/EclipseState.cpp:338
#13 0x0000000000745bb7 in Opm::EclipseState::EclipseState (this=0x7fffffffdad0, deck=...) at /home/kaib/OPM/debug/opm-parser/opm/parser/eclipse/EclipseState/EclipseState.cpp:131
#14 0x0000000000647060 in main (argc=2, argv=0x7fffffffdee8) at /home/kaib/OPM/debug/opm-parser/opm/parser/eclipse/Applications/opm-eclkwtest.cpp:71
```

**Comment by joakim-hove** [comment]
OK; I see - I have misguided you - sorry.

The table code will unconditionally access SI properties, you must have `"dimension" : "1"` on the `DATA` item.

**Comment by GitPaean** [comment]
It works. Thanks. I just updated the branch.

**Comment by joakim-hove** [comment]
OK good - let me know when to press the green.

**Comment by GitPaean** [comment]
Hi, some tests have been performed on the `opm-polymer` side. I think this PR is ready to be merged to me.

**Comment by joakim-hove** [comment]
Ok - merging.

**Pull request merged**
