### PR TITLE
Make Well+Schedule copyable

### PR DESCRIPTION
**Pull request by jokva**
Now that WellSet and GroupTree have been modified to no longer use internal references, we can make the Well object copyable and store it directly in the Schedule object.

### CODE REVIEW

**Comment by joakim-hove** [comment]
I will merge this when the ewoms build failure is fixed.

**Comment by joakim-hove** [comment]
jenkins build this with downstreams ewoms=94 opm-simulators=950 please

**Comment by joakim-hove** [comment]
jenkins build this with downstreams ewoms=94 opm-simulators=950 please

**Comment by jokva** [comment]
jenkins build this with downstreams ewoms=94 opm-simulators=950 please

**Comment by jokva** [comment]
jenkins build this with downstreams ewoms=94 opm-simulators=950 please

**Pull request merged**
