### PR TITLE
Added one-argument ParseContext constructor.

### PR DESCRIPTION
**Pull request by joakim-hove**

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this with downstreams please

**Comment by atgeirr** [comment]
Just one thing: one-argument constructors should be explicit unless you specifically want to have implicit conversion.

**Comment by joakim-hove** [comment]
> Just one thing: one-argument constructors should be explicit unless you specifically want to have implicit conversion.

Ehhh - well; it is marked as `explicit` in the header file.

**Comment by atgeirr** [comment]
> Ehhh - well; it is marked as explicit in the header file.

Yes of course! Sorry for the noise, I must have looked at the cpp file and not noticed.

**Comment by andlaus** [comment]
>> Ehhh - well; it is marked as explicit in the header file.
>
> Yes of course! Sorry for the noise, I must have looked at the cpp file and not noticed.

did you just deliver an argument that all function bodies should go beneath their declarations? ;)

**Pull request merged**
