### PR TITLE
UnitSystem: Add Support for PVT-M Unit Conventions

### PR DESCRIPTION
**Pull request by bska**
The PVT-M unit convention is essentially the same as the Metric collection, except that pressure values are measured in atmospheres rather than bars.

### CODE REVIEW

**Comment by joakim-hove** [comment]
This is beautifull - will certainly merge; just one minor detail/question - I guess a switch should be added here: https://github.com/OPM/opm-parser/blob/master/lib/eclipse/Deck/Deck.cpp#L137?

**Comment by bska** [comment]
> I guess a switch should be added here:

Ooooops.  You are of course correct.  I will update my patch set.  Thank you for pointing out the deficiency!

**Comment by bska** [comment]
> I will update my patch set

Updated in commit 754ac5a.  On a side note, I don't think the comment above that particular code section really reflects the structure of the implementation. The actual code seems to prefer METRIC above all other conventions.

**Comment by bska** [comment]
One more thing if I may: The "PVT-M" keyword is a perfectly good string, but it is not a valid C++ identifier.  While I **believe** that the JSON specification below is correct, I'd like to verify that.  Is there a good place to put a unit test to verify that the parser recognises "PVT-M" as a keyword?

--- 

```json
{"name" : "PVT_M" ,
 "sections" : ["RUNSPEC"],

 "deck_names" : [
  "PVT-M"
 ]
}
```

**Comment by joakim-hove** [comment]
> Is there a good place to put a unit test to verify that the parser recognises "PVT-M" as a keyword?

E.g. here: https://github.com/OPM/opm-parser/blob/master/lib/eclipse/tests/ParserTests.cpp

```C++

Parser parser;
const auto deck = parser.parseString( "PVT-M", ParseContext() );
BOOST_CHECK(  deck.hasKeyword( "PVT-M" ));
```

**Comment by bska** [comment]
>> Is there a good place to put a unit test to verify that the parser recognises "PVT-M" as a keyword?
>
> E.g. here ([`ParserTests.cpp`](https://github.com/OPM/opm-parser/blob/master/lib/eclipse/tests/ParserTests.cpp)).

Thanks.  I've updated my patch set to add the verification (commit 346c2d6).  I added tests for the other two unit conventions too, which prompted adding a JSON description for `LAB`.

**Comment by bska** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
jenkins chill please

**Comment by bska** [comment]
> jenkins chill please

:smile: 

Thanks a lot.

**Pull request merged**
