### PR TITLE
Rename parsemode

### PR DESCRIPTION
**Pull request by qilicun**
As discussed in https://github.com/OPM/opm-parser/pull/712

### CODE REVIEW

**Comment by qilicun** [comment]
Will fix this issue

**Comment by qilicun** [comment]
Finally， travis feels happy!
But the strange thing is that my local build with the latest opm-common will never build opm-parser/python folder. Does anyone know why?

**Comment by joakim-hove** [comment]
> But the strange thing is that my local build with the latest opm-common will never build opm-parser/python folder

The python code is not built by default; you must pass `-DENABLE_PYTHON=ON` during the configure step.

**Comment by qilicun** [comment]
>you must pass -DENABLE_PYTHON=ON during the configure step.

Thanks for noticing.

**Comment by joakim-hove** [comment]
OK - good; this was a massive search-replace effort. I'll run around pressing green buttons.

**Pull request merged**
