### PR TITLE
Remove shared_ptr Well alias, make Schedule interface more consistent

### PR DESCRIPTION
**Pull request by jokva**
I'm doing some work on output that works with the parser, and I keep finding issues with the parser interface.

This patch set smooths some of the edges in the `Schedule` interface by making `Well` and `Group`-functions have uniform behaviour w.r.t. types. Since this soft-breaks the interface anyway, it's about time to retire `WellPtr` and friends.

Ideally I'd make the Well communication here a reference right away, but that would mean a lot of `->` to `.` changes, which is work for another day. By removing the ownership sharing (which was a ruse) from the interface, replacing `shared_ptr` with raw pointers, little changes in client code.

### CODE REVIEW

**Comment by atgeirr** [comment]
The PRs in opm-core and opm-simulators look ok (minor nitpick about auto over-use aside). I tried to focus on possible ownership issues, and could not find any problems in my quick look.

I agree about using references, and also agree that it can come later.

**Comment by jokva** [comment]
There aren't any because all this data is owned by, and was always owned by, `EclipseState`.

**Comment by atgeirr** [comment]
> There aren't any because all this data is owned by, and was always owned by, EclipseState.

Clients could have participated in ownership by retaining the shared_ptr. There is no way to guarantee that does not happen. However, it seems to not actually happen with the objects here.

**Comment by jokva** [comment]
Doesn't matter since we mandate `EclipseState` liveness. There's no reason for clients to participate in ownership, and it was always a bug in my opinion. I've yet to read a single piece of code in opm that uses `shared_ptr` for actual shared ownership.

**Pull request merged**
