### PR TITLE
EclipseState: refactor constructor

### PR DESCRIPTION
**Pull request by joakim-hove**
Minor refactoring of EclipseState constructor. To prepare for external Schedule.

Depends on: 
https://github.com/OPM/opm-output/pull/204
https://github.com/OPM/opm-core/pull/1176

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this with downstreams please

**Comment by joakim-hove** [comment]
enkins build this with downstreams please

**Comment by atgeirr** [comment]
jenkins build this with downstreams please

**Comment by joakim-hove** [comment]
jenkins build this opm-output=204 with downstreams please

**Comment by joakim-hove** [comment]
jenkins build this opm-output=204 opm-core=1176 with downstreams please

**Comment by joakim-hove** [comment]
jenkins build this opm-output=204 opm-core=1176 with downstreams please

**Pull request merged**
