### PR TITLE
Add polymer to phase class in Runspec

### PR DESCRIPTION
**Pull request by totto82**
Also add test for solvent in RunspecTests.

### CODE REVIEW

**Comment by joakim-hove** [comment]
Looks good - can be merged when the build testing is green.

**Comment by joakim-hove** [comment]
jenkins builds this with downstreams please

**Comment by joakim-hove** [comment]
jenkins builds this with downstreams please

**Comment by akva2** [comment]
i s/builds/build for you.

**Comment by joakim-hove** [comment]
> i s/builds/build for you.

Thank you.

**Comment by totto82** [comment]
Can this be merged now? Or do you want me to change something?

**Comment by joakim-hove** [comment]
> Can this be merged now?

Absolutely - I tried to indicate that you should merge it when it was ready; but I can see that was not 100% clear; the only reason I held back was that I was not certain of the interaction with the other PR's.

@totto82: please merge!

**Pull request merged**
