### PR TITLE
WIP: Extract schedule

### PR DESCRIPTION
**Pull request by joakim-hove**
Depends on: 

https://github.com/OPM/opm-output/pull/207
https://github.com/OPM/opm-grid/pull/285
https://github.com/OPM/opm-core/pull/1182
https://github.com/OPM/ewoms/pull/233
https://github.com/OPM/opm-simulators/pull/1315

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this with downstreams opm-parser=1138 opm-grid=285 please

**Comment by joakim-hove** [comment]
jenkins build this with downstreams opm-output=207 opm-grid=285 please

**Comment by joakim-hove** [comment]
jenkins build this with downstreams opm-output=207 opm-grid=285 please

**Comment by joakim-hove** [comment]
jenkins build this with downstreams opm-output=207 opm-grid=285 please

**Comment by joakim-hove** [comment]
jenkins build this with downstreams opm-output=207 opm-grid=285 please

**Comment by joakim-hove** [comment]
jenkins build this with downstreams opm-output=207 opm-grid=285 please

**Comment by joakim-hove** [comment]
jenkins build this with downstreams opm-output=207 opm-grid=285 please

**Comment by joakim-hove** [comment]
enkins build this with downstreams opm-output=207 opm-grid=285 opm-core=1182 please

**Comment by joakim-hove** [comment]
jenkins build this with downstreams opm-output=207 opm-grid=285 opm-core=1182 please

**Comment by joakim-hove** [comment]
jenkins build this with downstreams opm-output=207 opm-grid=285 opm-core=1182 please

**Comment by joakim-hove** [comment]
jenkins build this with downstreams opm-output=207 opm-grid=285 opm-core=1182 ewoms=233 please

**Comment by joakim-hove** [comment]
jenkins build this with downstreams opm-output=207 opm-grid=285 opm-core=1182 ewoms=233 opm-simulators=1315 please

**Comment by joakim-hove** [comment]
jenkins build this with downstreams opm-output=207 opm-grid=285 opm-core=1182 ewoms=233 opm-simulators=1315 please

**Comment by joakim-hove** [comment]
jenkins build this with downstreams opm-output=207 opm-grid=285 opm-core=1182 ewoms=233 opm-simulators=1315 please

**Comment by joakim-hove** [comment]
jenkins build this with downstreams opm-output=207 opm-grid=285 opm-core=1182 ewoms=233 opm-simulators=1315 please

**Comment by joakim-hove** [comment]
jenkins build this with downstreams opm-output=207 opm-grid=285 opm-core=1182 ewoms=233 opm-simulators=1315 please

**Comment by joakim-hove** [comment]
enkins build this with downstreams opm-output=207 opm-grid=285 opm-core=1182 ewoms=233 opm-simulators=1315 please

**Comment by joakim-hove** [comment]
jenkins build this with downstreams opm-output=207 opm-grid=285 opm-core=1182 ewoms=233 opm-simulators=1315 please

**Comment by joakim-hove** [comment]
jenkins build this with downstreams opm-output=207 opm-grid=285 opm-core=1182 ewoms=233 opm-simulators=1315 please

**Comment by joakim-hove** [comment]
jenkins build this with downstreams opm-output=207 opm-grid=285 opm-core=1182 ewoms=233 opm-simulators=1315 please

**Comment by joakim-hove** [comment]
jenkins build this with downstreams opm-output=207 opm-grid=285 opm-core=1182 ewoms=233 opm-simulators=1315 please

**Comment by joakim-hove** [comment]
jenkins build this with downstreams opm-output=207 opm-grid=285 opm-core=1182 ewoms=233 opm-simulators=1315 please

**Comment by joakim-hove** [comment]
jenkins build this with downstreams opm-output=207 opm-grid=285 opm-core=1182 ewoms=233 opm-simulators=1315 please

**Comment by joakim-hove** [comment]
jenkins build this with downstreams opm-output=207 opm-grid=285 opm-core=1182 ewoms=233 opm-simulators=1315 please

**Comment by joakim-hove** [comment]
jenkins build this with downstreams opm-output=207 opm-grid=285 opm-core=1182 ewoms=233 opm-simulators=1315 please

**Comment by atgeirr** [comment]
I'll start testing this now.

**Comment by atgeirr** [comment]
> I'll start testing this now.

Testing complete, source of downstream test failures found (see the opm-simulators PR). Apart from that, the PRs seem ready to be merged as soon as Jenkins is green.

**Comment by joakim-hove** [comment]
jenkins build this with downstreams opm-output=207 opm-grid=285 opm-core=1182 ewoms=233 opm-simulators=1315 please

**Pull request merged**
