### PR TITLE
add multiconfiguration support to jenkins build script

### PR DESCRIPTION
**Pull request by akva2**
also unifies build.sh and build-pr.sh and gets rid of build-opm-parser.sh.

Depends on https://github.com/OPM/opm-common/pull/169 and changes to the jenkins configuration at http://ci.opm-project.org

### CODE REVIEW

**Comment by pgdr** [comment]
Is there a reason why `build.sh` isn't put in opm-common, and then all we have to do in parser is to "git clone common" && `opm-common/jenkins/build.sh`?  I think that's what we do with Travis, and that works quite well.

**Comment by akva2** [comment]
yes. it works because travis is "stupid", it doesn't keep track of the forks in the dependency trees. i do not want to make that simplification, so i need to keep the list of up / downstreams in each module.

**Comment by akva2** [comment]
@joakim-hove due to this being sensitive to the order of changes and needing syncronized external changes to the jenkins server, i request authority to merge myself when deemed ready.

**Comment by akva2** [comment]
jenkins build this serial please

**Comment by akva2** [comment]
jenkins build this serial opm-common=169 please

**Comment by akva2** [comment]
this is ready for merge. i have made an attempt at jenkins to keep the builder working in the mean time, but no guarantees how well those attempts work.

**Comment by joakim-hove** [comment]
> due to this being sensitive to the order of changes and needing syncronized external changes to the jenkins server, i request authority to merge myself when deemed ready.

Sorry - I lost this one. *Yes 007* - you have the permission to merge!

**Pull request merged**
