### PR TITLE
Rename targets

### PR DESCRIPTION
**Pull request by akva2**
- rename opm-json to opmjson
- rename Parser to opmparser

this for consistency with other modules. depends on https://github.com/OPM/opm-parser/pull/469

### CODE REVIEW

**Comment by joakim-hove** [comment]
Hmmm - not green?!

**Comment by akva2** [comment]
rebased.

**Comment by joakim-hove** [comment]
Hmmm - I guess the `Findopm-parser.cmake` also needs to be updated?

**Comment by akva2** [comment]
yes as such. I forgot, ref phone conversation..

**Pull request merged**
