### PR TITLE
Remove python bindings

### PR DESCRIPTION
**Pull request by JensGM**
The Sunbeam project (available at https://github.com/Statoil/sunbeam)
is replacing these python bindings making them obsolete. They are
deprecated and no longer maintained.

### CODE REVIEW

**Comment by akva2** [comment]
please remove from debian/control as well. the package entries and the python packages in build-depends. same deal for redhat/

**Comment by atgeirr** [comment]
Interesting! What is the aim of the sunbeam project, and how does it differ from the existing python bindings?

**Comment by joakim-hove** [comment]
> What is the aim of the sunbeam project, 

The aim of the sunbeam project is to create fully functional Python wrappers for opm-parser, to be able to replace numerous internal custom parsers. Hopefully this will also feed back to increased testing and robustness of the main C++ codebase.

> and how does it differ from the existing python bindings?

Using Boost Python to create bindings, developed outside of opm-parser and hopefully maintained:-)

**Comment by JensGM** [comment]
@akva2 Done, updated or deleted files CMakeLists.txt, debian/control, debian/python-opm-parser.install, debian/rules, redhat/opm-parser.spec and travis/build-and-test-opm-parser.sh

**Comment by akva2** [comment]
thanks. however there was still some more things left, please pick https://github.com/akva2/opm-parser/commit/e15e65ca9316a0f0ecb64d26d0a4209e73782847

**Comment by akva2** [comment]
you should probably squash, idc about credits.

**Comment by akva2** [comment]
now the commit is gone ;) 

just in case:
git checkout remove_python_bindings
git pull https://github.com/akva2/opm-parser remove_python
git rebase -i HEAD~2
change 'pick' to 'f' for the last entry.
git push -f the branch.

**Comment by JensGM** [comment]
@akva2 Alright it's done, thanks for the help! Unsure what went wrong when i tried to rebase the first time.

**Comment by akva2** [comment]
quirks happen, all good now :)

**Pull request merged**
