### PR TITLE
Thpres

### PR DESCRIPTION
**Pull request by joakim-hove**
Using a map based approach to internalizing THPRES values.

### CODE REVIEW

**Comment by joakim-hove** [comment]
> Any reason not to implement this as

Not really - I considered that; the immediate reason I did not do it was that then the tests:
```C++
if (deck->hasKeyword("EQLOPTS") && deck->hasKeyword("THPRES")) 
....
```
had to be moved to the `SimulationConfig` object.

**Comment by bska** [comment]
>> Any reason not to implement this as [...]
>
> Not really - I considered that; the immediate reason I did not do it was that then the tests:

Sorry, I don't understand why.  The member function `SimulationConfig::hasThresholdPressure()` already referenced `m_ThresholdPressure` so whatever constraints where in place do not change by switching to my suggested implementation.

**Comment by joakim-hove** [comment]
>Sorry, I don't understand why. 

Well - I might be the one misunderstanding here? As I understand it the test 
```
m_thresholdPressure->empty()
```

check whether the smart pointer points to *something*? The current implementation will unconditionally create a `ThresholdPressure` instance - so the `m_thresholdPressure` will always point to *something*. However if the deck does not contains any `THPRES` configuration the `ThresholdPressure` instance will have zero elements - i.e. `size() == 0`.

That said - your approach could very well be a better implementation.

**Comment by bska** [comment]
> As I understand it the test
```C++
m_thresholdPressure->empty()
```
check whether the smart pointer points to something?

Ah, right.  No, that's not the case.  The above is equivalent to
```C++
(*m_thresholdPressure).empty()
```
(i.e., call `empty()` on the object contained in the pointer).  You're probably thinking of the conceptual statement
```
m_thresholdPressure.empty()
```
(which doesn't compile because `std::shared_ptr<>` doesn't have an `empty()` method).  That would inspect the pointer itself rather than the contained object.

> the `m_thresholdPressure` will always point to *something*. However if the deck does not contains any THPRES configuration the `ThresholdPressure` instance will have zero elements - i.e., `size() == 0`.

Okay, if there is no `ThresholdPressure::empty()` then I'd just say
```C++
bool SimulationConfig::hasThresholdPressure() const {
    return m_ThresholdPressure->size() > 0;
}
```

**Comment by joakim-hove** [comment]
> You're probably thinking of the conceptual statement

yes - that was what I was thinking of.

**Pull request merged**
