### PR TITLE
Opm 199 IOConfig

### PR DESCRIPTION
**Pull request by chflo**
Added IOConfig class. The class holds data about input and output configuration; currently the following is supported:
- If UNIFIN/UNIFOUT/FMTIN/FMTOUT is set
- Should restart file be written at a given timestep (RPTRST keyword is supported)
- Should EGRID file be written (GRIDFILE / NOGGF keyword)
- Should INIT file be written (INIT keyword)
A const pointer to the IOConfig object can be fetched from EclipseState

### CODE REVIEW

**Comment by joakim-hove** [comment]
This looks very good - just one last thing. My suggestion is that the  `IOConfig` class gets the ?`input_path` argument as input:

```
IOConfig::IOConfig( deck , std::string& input_path) { 
   ...
}
```

**Comment by GitPaean** [comment]
With this PR, the Cartesian grid we have been using for some while failed. 

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  IOConfig: Reading GRIDFILE keyword from GRID section: Output of GRID file is not supported
Aborted
```

The grid file we are using is as follows for your testing. 
```
RUNSPEC

DIMENS
20 1 5 /

GRID

NEWTRAN

GRIDFILE
  2  /

GRIDUNIT
METRES  /

INIT

--------------------------------------------------------
--
--  	Grid
--
--------------------------------------------------------

DX
100*200 /
DY
100*200 /
DZ
100*25 /

TOPS
20*2500
20*2525
20*2550
20*2575
20*2600 /
```

**Comment by joakim-hove** [comment]
Well - this is because of the `GRIDFILE` keyword. This:
```txt
GRIDFILE
  2  /
```
asks for output of a `.GRID` file in extended format - which has previously been ignored.The `.GRID` format is an old format which we do not support, instead we support the (not very) new `.EGRID` format. Output of an `.EGRID` file is default - so just removing the `GRIDFILE` keyword should solve this problem. If you insist on using the `GRIDFILE` keyword it should be:

```txt
GRIDFILE
  0  1 /
```

**Comment by GitPaean** [comment]
Thanks for pointing out. I will try.

**Comment by atgeirr** [comment]
I suggest that we do this:
 - Reduce the severity of the "output of GRID file not supported" to a warning.
 - Change the input file in question anyway to avoid getting an annoying warning every time.

**Comment by chflo** [comment]
OK, I will change it to a warning

**Pull request merged**
