### PR TITLE
adding a few summary keywords

### PR DESCRIPTION
**Pull request by GitPaean**
WOVPT, WOVIR, WOVIT, WWVPR, WWVPT, WWVIR, WWVIT, WGVPR, WGVPT, WGVIR,
WGVIT

basically they are the keywords for reservoir phase rates summary output.

I guess to output them with OPM, we need to add them in opm-output and do more things in opm-simulators. I am not sure how the summary keyword system works, please correct me if I am wrong. 

How to add the related FIELD and GROUP keywords? Do we need to do them in opm-parser, or just in opm-output?

### CODE REVIEW

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
> I guess to output them with OPM, we need to add them in opm-output and do more things in opm-simulators.

This is correct.

**Comment by joakim-hove** [comment]
> How to add the related FIELD and GROUP keywords? 

You need to add them to the `FIELD_PROBE` and `GROUP_PROBE` keywords, just like you have done with the `WELL_PROBE` keyword already. And then subsequently updates to opm-output.

I am happy to merge this now; but I will leave it open in case you want to add the corresponding FIELD and GROUP keywords?

**Comment by GitPaean** [comment]
> I am happy to merge this now; but I will leave it open in case you want to add the corresponding FIELD and GROUP keywords?

Please leave it open and I will add the FIELD and GROUP related keywords later today.  I did not find these two files when I created this PR.

**Comment by GitPaean** [comment]
The things are little more messy to me now. It looks like a lot of keywords are only available for E100 while not E300. All the related keywords in `FIELD` and `GROUP` are not available for E100. So the new commit message is 
```
add WWVIR, WGVPR and WGVIR, and removing WOVPR
```

the commit has been updated.

**Comment by GitPaean** [comment]
> jenkins build this please

**Comment by GitPaean** [comment]
jenkins build this please

**Comment by GitPaean** [comment]
I am done updating this PR. Merge anytime you want.

**Comment by joakim-hove** [comment]
Ok - I will, busy today though.

**Pull request merged**
