### PR TITLE
Special case unity unit transformations.

### PR DESCRIPTION
**Pull request by joakim-hove**
This a minor preparation to facilitate bitwise correct restarts.

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this with downstreams ert=1406 please

**Comment by jokva** [comment]
Isn't identity already == 1 in the unit table?

**Comment by joakim-hove** [comment]
> Isn't identity already == 1 in the unit table?

Absolutely - and this whole PR might be unnecessary - the reason was that I wanted a guarantee that 
```
units::from_si( measure::identity , x ) == x
```
bitwise. I don't know if the IEEE representation is guaranteed to represent 1.0 exactly?

**Comment by jokva** [comment]
You can assume that.

>  Despite these examples, there are useful optimizations that can be done on floating-point code. First of all, there are algebraic identities that are valid for floating-point numbers. Some examples in IEEE arithmetic are x + y = y + x, 2 ×  x = x + x, 1 × x = x, and 0.5× x = x/2. However, even these simple identities can fail on a few machines such as CDC and Cray supercomputers. Instruction scheduling and in-line procedure substitution are two other potentially useful optimizations.

https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html

A question though: why is bitwise equality important?

**Comment by joakim-hove** [comment]
> A question though: why is bitwise equality important?

That was a minor preparation for bitwise correct restart.

**Comment by joakim-hove** [comment]
OK - @jokva: feel free to close this if you feel that is appropriate; or merge it of course. As long as I have a reasonable IEEE guarantee that:
```txt
1.0 *x == x
```
I am satisfied.

**Comment by jokva** [comment]
It doesn't seem like it's *mandated* by the standard (because they very rarely mandate these kinds of properties), but as far as potential portability issues go this seems like a non-problem. If proper portability and bitwise-representation-on-disk actually becomes an issue we can use `numeric_limits` to statically determine whether or not some particular representation is used, but regardless we need to do something to make restart files (or others) portable between platforms, since as of right now everything just dumps its native-ish float format.

**Comment by akva2** [comment]
IEEE guarantees exact representation of +- 2^0, but all bets are off after a flop.

**Comment by joakim-hove** [comment]
> IEEE guarantees exact representation of +- 2^0, but all bets are off after a flop.

So @akva2: what is your opinion - does this PR make sense, or is it just over something? I am happy to see it closed if it does not make sense.

**Comment by akva2** [comment]
i do not think this will help much in practice. it would just aid a synthetic test of what you wrote above ^^. all these numbers will have calculations performed on them "downstream". the only case where this guarantee is useful is that you can do default values like 1.0, and if no operations are done you are guaranteed that you can use if (a == 1.0) type checks.

**Comment by joakim-hove** [comment]
> all these numbers will have calculations performed on them "downstream"

Well - in my opinion it should be possible to formulate the restart code so that the bytes lifted from disk are passed all the way to the simulator with a single flop.

**Comment by akva2** [comment]
probably, but then we would need to some derived data as well, which is regenerated in the simulator upon restart.

**Comment by joakim-hove** [comment]
>but then we would need to store some derived data as well, which is regenerated in the simulator upon restart.

Closing this for now.

**Pull request closed without merging**
