### PR TITLE
Add keywords for solvent model

### PR DESCRIPTION
**Pull request by totto82**
This PR adds the necessary keywords for the solvent model

### CODE REVIEW

**Comment by joakim-hove** [comment]
Sorry - about the slow reply. I think you have used the keyword `SPECIAL` incorrect - as I understand the manual the `SPECIAL` flag in the keyword documentation indicates that a keyword is only available as part of separately licensed Eclipse extension, there is no `SPECIAL` section?!

**Comment by totto82** [comment]
I noticed that the SPECIAL keyword was specified for the some of the polymer keywords, (See for instance PLYROCK) and did the same for the solvent keywords.

**Comment by joakim-hove** [comment]
>I noticed that the SPECIAL keyword was specified for the some of the polymer keywords

Yes - I know; it should be removed from the polymer keywords as well.

**Comment by totto82** [comment]
SPECIAL is removed from this PR

**Comment by joakim-hove** [comment]
Merging

**Pull request merged**
