### PR TITLE
pass OPM_DATA_ROOT in jenkins builds

### PR DESCRIPTION
**Pull request by akva2**
ref https://github.com/OPM/opm-simulators/issues/643

do let me test run it before merge.

### CODE REVIEW

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
jenkins build this please

**Comment by akva2** [comment]
there we go. the jenkins builder will now include the integration tests using opm-data. to conserve resources, opm-data is updated at midnight. consequently, there is no trigger support to run against a specific pr in opm-data. 

(noise was caused by differing workspace paths on the opm jenkins and newer versions i'm used to working with.)

**Comment by atgeirr** [comment]
> opm-data is updated at midnight

I assume this means there is an opm-data area that is shared between all Jenkins jobs?

**Comment by akva2** [comment]
yes.

**Comment by akva2** [comment]
please hold a bit on the merge. i'm adding trigger support (where it clones only if necessary).

**Comment by akva2** [comment]
jenkins build this opm-common=108 please

**Comment by akva2** [comment]
okay. all green. there is now trigger support for opm-data. use with caution! the shared copy is used whenever possible (ie nothing specified in trigger). note that the companion https://github.com/OPM/opm-common/pull/108 needs to be merged first.

**Pull request merged**
