### PR TITLE
Skip random text when unknown keyword.

### PR DESCRIPTION
**Pull request by joakim-hove**

### CODE REVIEW

**Comment by joakim-hove** [comment]
jenkins build this with downstreams ert=1467 please

**Comment by joakim-hove** [comment]
jenkins build this with downstreams please

**Comment by joakim-hove** [comment]
jenkins build this with downstreams please

**Comment by joakim-hove** [comment]
@atgeirr : Could you give this a spin?

**Comment by atgeirr** [comment]
> @atgeirr : Could you give this a spin?

Yes, but not until next week, unfortunately.

**Comment by atgeirr** [comment]
Looks like it works as hoped! I'll check with Halvor for the final verdict.

**Pull request merged**
