### PR TITLE
update path due to opm-data restructuring

### PR DESCRIPTION
**Pull request by akva2**
up/down/sidestream of https://github.com/OPM/opm-data/pull/217

### CODE REVIEW

**Comment by atgeirr** [comment]
Should it not be polymer_simple2D, not simple2D?

**Comment by akva2** [comment]
doh. yes. had fixed it locally but forgot to recommit.

**Comment by akva2** [comment]
this missed a piece

**Comment by akva2** [comment]
there we go. there were two references to the file, something i didn't expect.

**Comment by joakim-hove** [comment]
OK - this should be merged at the appropriate time; by someone :smile:

**Comment by atgeirr** [comment]
> OK - this should be merged at the appropriate time; by someone 😄

Jenkins was green (in opm-data) so this is the time...

**Pull request merged**
