### PR TITLE
adding FLD to the ControlEnum of GroupProduction

### PR DESCRIPTION
**Pull request by GitPaean**
Should not have any bad impact to other parts of OPM.

### CODE REVIEW

**Comment by joakim-hove** [comment]
> Should not have any bad impact to other parts of OPM.

Famous last words :grin: Will merge as soon as Travis: :white_check_mark:

**Comment by GitPaean** [comment]
I do not think the failure is related to this PR
```
The following tests FAILED:
	 21 - compareECLFiles_SPE1CASE2 (Failed)
	 22 - compareECLFiles_SPE3CASE1 (Failed)
	 23 - compareECLFiles_SPE9_CP_SHORT (Failed)
Errors while running CTest
The command "opm-common/travis/build-and-test.sh opm-parser" exited with 8.
Done. Your build exited with 1.
```

**Comment by joakim-hove** [comment]
jenkins build this with downstreams please

**Comment by akva2** [comment]
the jenkins job above will fail, which again is most likely a false positive. this due to the fact that opm-data is only updated on a nightly schedule and i forgot to manually kick off the jenkins job after the opm-data update was merged. i did it now but was too late to salvage the job.  personally i would *really* like to kill this complication and have a post-merge "builder" for opm-data, but i have done as instructed.

a theory is that travis managed to clone an updated opm-data, which was merged against my instructions without updating the others in tandem. there was a gap of about 30min where i had my lunch. it would be rather useful to get some logging of what travis is actually building.

**Comment by akva2** [comment]
right. it was likely all my fault. in the confusion i forgot to merge the opm-common bits everything else built on. shame on me.

**Comment by alfbr** [comment]
> which was merged against my instructions

My apologies, I did not notice the hold off request. I will read more carefully next time.

**Comment by akva2** [comment]
No worries. Next time i will be a man and handle the entire merge on my own ;) i tend to suck hard at serializing brain state in pr descriptions.

**Comment by joakim-hove** [comment]
jenkins build this with downstreams please

**Comment by akva2** [comment]
last run is not a false positive as such. but it is not due to this commit. the failures are caused by https://github.com/OPM/opm-core/pull/1065 / https://github.com/OPM/opm-simulators/pull/833

not sure if these changes in the output was expected, investigating..

**Comment by akva2** [comment]
regression identified, https://github.com/OPM/opm-simulators/pull/834

**Comment by akva2** [comment]
jenkins build this with downstreams please

**Comment by akva2** [comment]
the two failures are unrelated, ref https://github.com/OPM/opm-grid/pull/234

**Comment by joakim-hove** [comment]
The mpi build of opm-grid fails on jenkins:
```
Test project /var/lib/jenkins/workspace/opm-parser-PR-builder/mpi/build-opm-grid
 1/10 Test  #1: distribution .....................***Failed    0.11 sec    
 7/10 Test  #7: partition_iterator ...............***Failed    0.07 sec
```
is that "expected"`?

**Comment by akva2** [comment]
see my last comment.

**Comment by joakim-hove** [comment]
OK - this is "green enough". Merging.

**Pull request merged**
