### PR TITLE
3D Properties Test: Check Radial Tensor Support

### PR DESCRIPTION
**Pull request by bska**
Mostly for completeness since the underlying implementation just piggy-backs on the existing support for Cartesian tensors.

This should really have been part of #1094.  My apologies for not thinking of this sooner.

### CODE REVIEW

**Comment by bska** [comment]
jenkins build this please

**Comment by joakim-hove** [comment]
Yes - the reason I never added the `GridProperties` `PERMR` and `PERMTHT` was that I was a bit uncertain about the expected alias behaviour - and then I forgot the whole thing. By reading the ECLIPSE documentation you could get the impression `PERMX <-> PERMR` and `PERMY <-> PERMTHT` - whereas our implementation implies that they are separate objects which can be manipulated independently. 

To actully implement "property reference semantics" is probably not worth it?

**Comment by bska** [comment]
> To actually implement "property reference semantics" is probably not worth it?

Agreed.  I thought it was more of the case that one (i.e., a simulation case) would use `PERM{R,THT}` when the `RUNSPEC` has `RADIAL` and `PERM{X,Y}` otherwise.

I guess it ultimately comes down to whether or not the simulator, or at least the transmissibility calculation code, wants to be agnostic to the specific nature of the grid.  While that could be a goal from a software engineering point of view, the formulae for computing transmissibilities really are different in the two coordinate systems and trying to hide that behind permeability aliases would probably  just obscure the implementation.

**Comment by joakim-hove** [comment]
> Agreed. I thought it was more of the case that one (i.e., a simulation case) would use PERM{R,THT} when the RUNSPEC has RADIAL and PERM{X,Y} otherwise.

That would make sense - hopefully you are right; I thought it was more like the keywords `PERMR` and `PERMX`could be interchanged freely. Anyway - we'll burn that if we ever get there.

**Pull request merged**
