### PR TITLE
EndpointScaling: will create default if SWATINIT

### PR DESCRIPTION
**Pull request by joakim-hove**

### CODE REVIEW

**Comment by joakim-hove** [comment]
@totto82 : Will you merge this when/if you are happy.

**Comment by totto82** [comment]
Thanks. Is testing this now.

**Comment by joakim-hove** [comment]
Merging after communication with @totto82

**Comment by akva2** [comment]
this broke the 'equil' test in opm-core.

**Comment by pgdr** [comment]
Yes, we saw now that Travis actually timed out _before_ finishing opm-core.

**Pull request merged**
